config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }

  resources :studytimes do
    collection do
      get 'search_users'
    end
  end

  get '/studytimes/user/:user_name', to: 'studytimes#user_studytime', as: 'user_studytime'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/users/guest_login", to: "users/sessions#guest_login"
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/studytime.rb
class Studytime < ApplicationRecord
    has_one_attached :image
    scope :today, -> { where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }
    #validates :user_id, {presence: true}

    attr_accessor :search_users

    def users
        return Studytime.find_by(id: self.id)
    end
    
end

app/controllers/studytimes_controller.rb
class StudytimesController < ApplicationController
  before_action :set_studytime, only: %i[ show edit update destroy ]

  

  # GET /studytimes or /studytimes.json
  def index
    user_studytimes = Studytime.where(user_id: current_user.id).order(created_at: :desc)
    @studytimes = user_studytimes.page(params[:page]).per(12)
    @calc_studytimes = Studytime.all.order(created_at: :desc)
    @today_studytimes = @calc_studytimes.today
    @serch_other_users_studytimes = Studytime.where.not(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(12)

    if user_signed_in?
      #今日の勉強時間の"時間"と"分"の合計をそれぞれ取得し計算する
      @today_studytime_hours = @today_studytimes.where(user_id: current_user.id).sum(:studytime_hours)
      @today_studytime_minutes = @today_studytimes.where(user_id: current_user.id).sum(:studytime_minutes)
      @todays_total_studytime_hours = @today_studytime_hours + (@today_studytime_minutes / 60)
      @todays_total_studytime_minutes = @today_studytime_minutes % 60
      #今までの勉強時間の"時間"と"分"の合計をそれぞれ取得し計算する
      @all_studytime_hours = @calc_studytimes.where(user_id: current_user.id).sum(:studytime_hours)
      @all_studytime_minutes = @calc_studytimes.where(user_id: current_user.id).sum(:studytime_minutes)
      @total_all_studytime_hours = @all_studytime_hours + (@all_studytime_minutes / 60)
      @total_all_studytime_minutes = @all_studytime_minutes % 60
    end
  end

  # GET /studytimes/1 or /studytimes/1.json
  def show
    @studytime = Studytime.find(params[:id])
  end

  # GET /studytimes/new
  def new
    @studytime = Studytime.new
  end

  # GET /studytimes/1/edit
  def edit
    @studytime = Studytime.find(params[:id])
  end

  # POST /studytimes or /studytimes.json
  def create
    @user = User.find_by(id: session[:user_id])
    @studytime = Studytime.new(
      studytime_params
    )
    @studytime.user_id = current_user.id
    respond_to do |format|
      if @studytime.save
        format.html { redirect_to studytime_url(@studytime), notice: "記録が保存されました。" }
        format.json { render :index, status: :created, location: @studytime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @studytime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studytimes/1 or /studytimes/1.json
  def update
    respond_to do |format|
      if @studytime.update(studytime_params)
        format.html { redirect_to studytime_url(@studytime), notice: "記録を更新しました" }
        format.json { render :show, status: :ok, location: @studytime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @studytime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studytimes/1 or /studytimes/1.json
  #def destroy
  #  @studytime.destroy!

   # respond_to do |format|
    #  format.html { redirect_to studytimes_url, notice: "記録を削除しました" }
     # format.json { head :no_content }
    #end
  #end

  def destroy
    @studytime = Studytime.find(params[:id])
    @studytime.destroy
    redirect_to studytimes_path, notice: '記事が削除されました。'
  end

  def search_users
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
  

  def user_studytime
    @user = User.find_by(name: params[:user_name])
    if @user.nil?
      redirect_to studytimes_path, alert: "ユーザーが見つかりませんでした"
      return
    end
    @studytimes = Studytime.where(user_id: @user.id).order(created_at: :desc).page(params[:page]).per(12)
    @calc_studytimes = Studytime.all.order(created_at: :desc)
    @today_studytimes = @calc_studytimes.today

    @today_studytime_hours = @today_studytimes.where(user_id: @user.id).sum(:studytime_hours)
    @today_studytime_minutes = @today_studytimes.where(user_id: @user.id).sum(:studytime_minutes)
    @todays_total_studytime_hours = @today_studytime_hours + (@today_studytime_minutes / 60)
    @todays_total_studytime_minutes = @today_studytime_minutes % 60

    @all_studytime_hours = @calc_studytimes.where(user_id: @user.id).sum(:studytime_hours)
    @all_studytime_minutes = @calc_studytimes.where(user_id: @user.id).sum(:studytime_minutes)
    @total_all_studytime_hours = @all_studytime_hours + (@all_studytime_minutes / 60)
    @total_all_studytime_minutes = @all_studytime_minutes % 60
  end

  private

  def set_studytime
    @studytime = Studytime.find_by(id: params[:id])
  end

  def studytime_params
    params.require(:studytime).permit(:studytime_hours, :studytime_minutes, :memo, :image, :created_at).merge(user_id: current_user.id)
  end
  


  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studytime
      @studytime = Studytime.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def studytime_params
      params.require(:studytime).permit(:studytime_hours, :studytime_minutes, :memo, :image, :created_at).merge(user_id: current_user.id)
    end

end

app/helpers/studytimes_helper.rb
module StudytimesHelper
end

app/views/studytimes/_form.html.erb
<div class="form-container">
  <%= form_with(model: studytime) do |form| %>
    <% if studytime.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(studytime.errors.count, "error") %> prohibited this studytime from being saved:</h2>

        <ul>
          <% studytime.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <div class="form-group">
        <p>勉強時間</p>
        <%= form.select :studytime_hours,(0..23), id:"selectbox", class:"form-controll" %><strong>時間</strong>
        <!--<%= form.label :studytime_hours, :"時間" %>-->
        <%= form.select :studytime_minutes,(00..59), id:"selectbox", class:"form-controll" %><strong>分</strong>
        <!--<%= form.label :studytime_minutes, :"分"%>-->
      </div>

    <div class="form-group">
      <%= form.label :memo, :"メモ", style: "display: block", for: "create_memo" %>
      <%= form.text_area :memo, size:"30*5", id: 'create_memo', class: 'form-controll' %>
    </div>

    <div class="form-group">
      <%= form.label :image, :"画像", style: "display: block", for: "create_image" %>
      <%= form.file_field :image, id: 'create_image', class: 'form-controll' %>
    </div>

    <div class="action">
      <%= form.submit class:"btn btn-outline-info" %>
    </div>
  <% end %>
</div>

app/views/studytimes/_studytime.html.erb
<div id="<%= dom_id studytime %>">

  <p class="show-created_at"><%= studytime.created_at.strftime("%Y年%m月%d日 %H時%M分") %></p>
  
  <p>
    <strong>勉強時間</strong>
    <%= studytime.studytime_hours %>
    <strong>時間</strong>
    <%= studytime.studytime_minutes %>
    <strong>分</strong>
  </p>

  <p>
    <strong>メモ</strong> 
    <% unless current_page?(action: 'index')%>
      <%= studytime.memo %>
    <% else %>
      <%= studytime.memo.truncate(10, omission: '...') %>
    <% end %>
  </p>

</div>

app/views/studytimes/edit.html.erb
<h1 class="title">編集する</h1>

<%= render "form", studytime: @studytime %>


  <%= link_to @studytime, class:"btn btn_27", id:"goto-show" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
    </svg>
    記録詳細に戻る
  <% end %>

app/views/studytimes/index.html.erb
<p style="color: green"><%= notice %></p>
<script src="http://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>



<% if user_signed_in? %>
    <% if current_user.avatar? %>
      <%= image_tag current_user.avatar.url, class: "avatar-profile" %>
    <% else %>
      <%= image_tag '/assets/icon_user_1.png', class: "avatar-profile" %> 
    <% end %>
    <p class="index_user_name"><%= current_user.name %>さん</p>
  <div class="index_total_studytime">
    <p>今日の勉強時間：<%= @todays_total_studytime_hours %>時間<%= @todays_total_studytime_minutes %>分</p>
    <p>今までの勉強時間：<%= @total_all_studytime_hours %>時間<%= @total_all_studytime_minutes %>分</p>
  </div>

  <p><%= link_to new_studytime_path, class:"btn btn_27", id: "index_create_studytime" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
      </svg>
      記録する
    <% end %>
  </p>

  
  
  <div class="logout">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn btn_27" %>
  </div>
  <%= link_to "プロフィールを編集", edit_user_registration_path, class:"btn btn_27" %>

  <%= link_to "検索", search_users_studytimes_path, class:"btn btn_27" %>

  <div id="studytimes">
    <% @studytimes.each do |studytime| %>
      <% if studytime.user_id  == current_user.id %>
        <div class="g-col-6">
          <%= render studytime %>
          <p><%= link_to "記録の詳細", studytime, class: "btn_index_detail" %></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <footer class="pagination-container">
    <%= paginate @studytimes %>
  </footer>
<% else %>
  <h1 class="title">ようこそStudyLogへ!</h1>
  <h3>勉強時間を記録するにはログインが必要です！</h3>
  <%= link_to "ログイン画面へ", "/users/sign_in", class:"btn btn_27" %>
<% end %>




  

app/views/studytimes/index.js.erb
document.querySelector('#studytimes').insertAdjacentHTML('beforeend', '<%= j render @studytimes %>');
if (document.querySelector('#pagination')) {
  document.querySelector('#pagination').innerHTML = '<%= j paginate @studytimes %>';
}

app/views/studytimes/new.html.erb
<h1 class="titile">勉強時間を記録する</h1>

<%= render "form", studytime: @studytime %>

<br>

<div class="action">
  <%= link_to studytimes_path, class:"btn btn_27", id:"goto-top" do  %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
      <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146ZM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5Z"/>
    </svg>
    戻る
  <% end %>
</div>


<!--def index
    @studytimes = Studytime.all.order(created_at: :desc).page(params[:page]).per(12)
    @calc_studytimes = Studytime.all.order(created_at: :desc)
    @today_studytimes = @calc_studytimes.today
    if user_signed_in?
      #今日の勉強時間の"時間"と"分"の合計をそれぞれ取得し計算する
      @today_studytime_hours = @today_studytimes.where(user_id: current_user.id).sum(:studytime_hours)
      @today_studytime_minutes = @today_studytimes.where(user_id: current_user.id).sum(:studytime_minutes)
      @todays_total_studytime_hours = @today_studytime_hours + (@today_studytime_minutes / 60)
      @todays_total_studytime_minutes = @today_studytime_minutes % 60
      #今までの勉強時間の"時間"と"分"の合計をそれぞれ取得し計算する
      @all_studytime_hours = @calc_studytimes.where(user_id: current_user.id).sum(:studytime_hours)
      @all_studytime_minutes = @calc_studytimes.where(user_id: current_user.id).sum(:studytime_minutes)
      @total_all_studytime_hours = @all_studytime_hours + (@all_studytime_minutes / 60)
      @total_all_studytime_minutes = @all_studytime_minutes % 60
    end
  end-->

app/views/studytimes/search_users.html.erb
<%= search_form_for @q, url: search_users_studytimes_path, method: :get do |f| %>
  <div class="search-user-field">
    <%= f.label :name_cont, "ユーザーを検索" %>
    <%= f.search_field :name_cont %>
  </div>
  <div class="search-btn">
    <%= f.submit '検索', class:"btn btn-outline-info" %>
  </div>
<% end %>

<div class="centered-table-container">
  <table class="centered-table">
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="user-info">
            <%= image_tag(user.avatar_url || 'icon_user_1.png', class: "avatar") %>
            <span class="user-name"><%= link_to user.name, user_studytime_path(user_name: user.name) %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/studytimes/show.html.erb
  <p style="color: green"><%= notice %></p>

  <h1 clasx="title">記録詳細</h1>
  <div class="show-studytimes"><%= render @studytime %></div>

  <% if @studytime.image.attached?%>
    <div class="image-position">
      <strong>写真:</strong>
      <%= image_tag @studytime.image, class:"image" %> 
    </div>
  <% end %>

  <div class="btn-position">

      <%= link_to edit_studytime_path(@studytime), class:"btn btn_27" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
          <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
          <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
        </svg>
        編集
      <% end %>

      <%= link_to studytimes_path, class:"btn btn_27" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
          <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146ZM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5Z"/>
        </svg>
        トップへ戻る
      <% end %>
  </div>
  <%= button_to "削除", studytime_path(@studytime), id:"show_delete_position", class:"btn btn-outline-danger", method: :delete %>

app/views/studytimes/user_studytime.html.erb
<p style="color: green"><%= notice %></p>
<script src="http://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>


  <% if @user.avatar? %>
    <%= image_tag @user.avatar.url, class: "user-avatar-profile" %>
  <% else %>
    <%= image_tag 'icon_user_1.png', class: "user-avatar-profile" %> 
  <% end %>
  <p class="index_user_name"><%= @user.name %>さんの勉強記録</p>
<div class="index_total_studytime">
    <p>今日の勉強時間：<%= @todays_total_studytime_hours %>時間<%= @todays_total_studytime_minutes %>分</p>
    <p>今までの勉強時間：<%= @total_all_studytime_hours %>時間<%= @total_all_studytime_minutes %>分</p>
</div>




<div id="studytimes">
    <% @studytimes.each do |studytime| %>
      <% if studytime.user_id  == @user.id %>
        <div class="g-col-6">
          <%= render studytime %>
        </div>
      <% end %>
    <% end %>
</div>

<footer class="pagination-container">
  <%= paginate @studytimes %>
</footer>